playit (v0.15.26): 1765316587164 tunnel running, 1 tunnels registered


TUNNELS
wealth-fda.with.playit.plus:1053 => 127.0.0.2:3389 (proto: Tcp, port count: 1)
playit (v0.15.26): 1765316590314 tunnel running, 1 tunnels registered
